const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  selectFolder: () => ipcRenderer.invoke('select-folder'),
  readFolder: (folderPath) => ipcRenderer.invoke('read-folder', folderPath),
  translatePage: (args) => ipcRenderer.invoke('translate-page', args),
  saveTypesetImage: (args) => ipcRenderer.invoke('save-typeset-image', args),
  saveFacebookArchive: (args) => ipcRenderer.invoke('save-facebook-archive', args),
  savePageTranslation: (args) => ipcRenderer.invoke('save-page-translation', args),
  loadPageTranslation: (args) => ipcRenderer.invoke('load-page-translation', args),
  loadChapterQualityState: (args) => ipcRenderer.invoke('load-chapter-quality-state', args),
  saveChapterQualityState: (args) => ipcRenderer.invoke('save-chapter-quality-state', args),
  saveMemory: (args) => ipcRenderer.invoke('save-memory', args),
  loadMemory: (args) => ipcRenderer.invoke('load-memory', args),
  saveCustomMask: (args) => ipcRenderer.invoke('save-custom-mask', args),
  loadCustomMask: (args) => ipcRenderer.invoke('load-custom-mask', args),
  clearCustomMask: (args) => ipcRenderer.invoke('clear-custom-mask', args),
  saveCustomPaint: (args) => ipcRenderer.invoke('save-custom-paint', args),
  loadCustomPaint: (args) => ipcRenderer.invoke('load-custom-paint', args),
  clearCustomPaint: (args) => ipcRenderer.invoke('clear-custom-paint', args),
  listProjects: () => ipcRenderer.invoke('list-projects'),
  deleteProjectMapping: (args) => ipcRenderer.invoke('delete-project-mapping', args),
  renameChapter: (args) => ipcRenderer.invoke('rename-chapter', args),
  saveApiKey: (args) => ipcRenderer.invoke('save-api-key', args),
  saveAppSettings: (args) => ipcRenderer.invoke('save-app-settings', args),
  loadAppSettings: () => ipcRenderer.invoke('load-app-settings'),
  selectWatermark: (args) => ipcRenderer.invoke('select-watermark', args),
  loadWatermark: (args) => ipcRenderer.invoke('load-watermark', args),
  saveWatermarkSettings: (args) => ipcRenderer.invoke('save-watermark-settings', args),
  removeWatermark: (args) => ipcRenderer.invoke('remove-watermark', args),
  deletePageTranslation: (args) => ipcRenderer.invoke('delete-page-translation', args),
  listChapterTranslations: (args) => ipcRenderer.invoke('list-chapter-translations', args)
});
